Remove RecordingId class
Inline classes currently cause NoSuchMethodError in various situations.

Signed-off-by: Saurabh Sandav <justmailsaurabh@gmail.com>